# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here|
      short_hash=`git rev-parse --short=7 HEAD`
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: dockerhub
- task: Docker@2
  inputs:
    Dockerfile: '**/Dockerfile'
    command: 'buildAndPush'
    containerRegistry: dockerhub
    repository: rvsivadocker/demoapp:$(GIT_BRANCH),$(short_hash)
