name: CI for DemoAPP
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rvsivadocker/demoapp:${{ github.sha }}
    - name: Display docker images
      run : docker image ls
